// Información de prueba.
export default {
    products: [{
        _id: '1',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '2',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/d2.jpg',
        price: 70,
        brand: 'Nike',
        rating: 4.2,
        numReviews: 10,
        countInStock: 2,
    },
    {
        _id: '3',
        name: 'Formal Pants',
        category: 'Pants',
        image: '/images/d3.jpg',
        price: 80,
        brand: 'Nike',
        rating: 4.6,
        numReviews: 10,
        countInStock: 3,
    },
    {
        _id: '4',
        name: 'Formal Pants Cool',
        category: 'Pants',
        image: '/images/d4.jpg',
        price: 90,
        brand: 'Nike',
        rating: 4.8,
        numReviews: 11,
        countInStock: 2,
    },
    {
        _id: '5',
        name: 'Shirt Cool',
        category: 'Shirts',
        image: '/images/d5.jpg',
        price: 50,
        brand: 'Nike',
        rating: 4.2,
        numReviews: 1,
        countInStock: 3,
    },
    {
        _id: '6',
        name: 'Shirt',
        category: 'Shirts',
        image: '/images/d6.jpg',
        price: 30,
        brand: 'Nike',
        rating: 4.8,
        numReviews: 14,
        countInStock: 3,
    }]
}
